{{- if .Values.workerPool.enabled -}}
{{- if .Values.workerPool.jobs.helmRevisions.enabled -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: monitor-helm-release-revisions
spec:
  schedule: {{ .Values.workerPool.jobs.helmRevisions.schedule | quote }}
  jobTemplate:
    spec:
      backoffLimit: 5
      template:
        spec:
          serviceAccountName: {{ include "porter.fullname" . }}-worker-pool
          metadata:
            labels:
              app.kubernetes.io/name: monitor-helm-release-revisions
              app.kubernetes.io/instance: {{ .Release.Name }}
              app.kubernetes.io/part-of: worker-pool
          containers:
            - name: job
              image: busybox
              imagePullPolicy: IfNotPresent
              command:
              - curl 
              args:
              - -X 
              - POST 
              - "{{ include "porter.fullname" . }}-worker-pool.{{ .Release.Namespace }}/enqueue/helm-revisions-count-tracker"
          restartPolicy: Never
          concurrencyPolicy: Forbid
{{- end -}}
{{- end -}}
