{{- if .Values.workerPool.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "porter.fullname" . }}-worker-pool
spec:
  replicas: 1
  template:
    metadata:
    {{- with .Values.workerPool.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    spec:
      {{- with .Values.workerPool.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "porter.fullname" . }}-worker-pool
      securityContext:
        {{- toYaml .Values.workerPool.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.workerPool.securityContext | nindent 12 }}
          image: "{{ .Values.workerPool.image.repository }}:{{ .Values.workerPool.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.workerPool.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.workerPool.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "porter.fullname" . }}-worker-pool-env-configmap
            - secretRef:
                name: {{ include "porter.fullname" . }}-worker-pool-env-secret
          env:
          - name: ENCRYPTION_KEY
            valueFrom:
              secretKeyRef:
                name: {{ include "porter.fullname" . }}-api-server-keys
                key: db-encryption-key
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: {{ include "porter.fullname" . }}-db-secret
                key: host
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: {{ include "porter.fullname" . }}-db-secret
                key: name
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: {{ include "porter.fullname" . }}-db-secret
                key: user
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: {{ include "porter.fullname" . }}-db-secret
                key: password 
          resources:
            {{- toYaml .Values.workerPool.resources | nindent 12 }}
      {{- with .Values.workerPool.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.workerPool.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.workerPool.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
