apiVersion: v1
kind: Secret
metadata:
  name: {{ include "porter.fullname" . }}-nats-secret
  labels:
    {{- include "porter.labels" . | nindent 4 }}
type: Opaque
data:
  url: {{ .Values.server.nats.url | default "" | b64enc | quote }}
  username: {{ .Values.server.nats.username | default "" | b64enc | quote }}
  password: {{ .Values.server.nats.password | default "porter" | b64enc | quote }}
  ca.pem: {{ .Values.server.nats.caBase64 | quote }}
  client-key.pem: {{ .Values.server.nats.keyBase64 | quote }}
  client.pem: {{ .Values.server.nats.certBase64 | quote }}
