apiVersion: v1
kind: Secret
metadata:
  name: {{ include "porter.fullname" . }}-nats-secret
  labels:
    {{- include "porter.labels" . | nindent 4 }}
type: Opaque
data:
  url: {{ .Values.server.nats.host | default "" | b64enc | quote }}
  username: {{ .Values.server.nats.username | default "" | b64enc | quote }}
  password: {{ .Values.server.nats.password | default "porter" | b64enc | quote }}
  caValue: {{ .Values.server.nats.caValue | default "" | b64enc | quote }}
  keyValue: {{ .Values.server.nats.keyValue | default "" | b64enc | quote }}
  certValue: {{ .Values.server.nats.certValue | default "" | b64enc | quote }}
