apiVersion: v1
kind: Secret
metadata:
  name: {{ include "porter.fullname" . }}-nats-secret
  labels:
    {{- include "porter.labels" . | nindent 4 }}
type: Opaque
data:
  url: {{ .Values.server.nats.host | default "" | b64enc | quote }}
  username: {{ .Values.server.nats.username | default "" | b64enc | quote }}
  password: {{ .Values.server.nats.password | default "porter" | b64enc | quote }}
  caFile: {{ .Values.server.nats.caFile | default "" | b64enc | quote }}
  keyFile: {{ .Values.server.nats.caFile | default "" | b64enc | quote }}
  certFile: {{ .Values.server.nats.certFile | default "" | b64enc | quote }}
