{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "porter.fullname" . }}-redis-db-secret
  labels:
    {{- include "porter.labels" . | nindent 4 }}
type: Opaque
data:
  host: {{ .Values.server.redis.host | default "" | b64enc | quote }}
  port: {{ .Values.server.redis.port | b64enc }}
  username: {{ .Values.server.redis.username | default "porter" | b64enc | quote }}
  password: {{ .Values.server.redis.password | default "" | b64enc | quote }}
{{- end }}