{{- if .Values.workerPool.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "porter.fullname" . }}-worker-pool
  labels:
    {{- include "porter.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.workerPool.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "workerPool.selectorLabels" . | nindent 4 }}
{{- end }}
