{{- if .Values.server.storage.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "porter.fullname" . }}-storage-secret
  labels:
    {{- include "porter.labels" . | nindent 4 }}
type: Opaque
data:
  endpoint : {{ .Values.server.storage.endpoint | default "" | b64enc | quote }}
  accessKey: {{ .Values.server.storage.accessKey | default "" | b64enc | quote }}
  secretKey: {{ .Values.server.storage.secretKey | default "" | b64enc | quote }}
  bucketName: {{ .Values.server.storage.bucketName | default "" | b64enc | quote }}
{{- end }}