{{- if .Values.workerPool.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "porter.fullname" . }}-worker-pool-env-configmap
  labels:
    {{- include "porter.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.workerPool.port | quote }}
  SQL_LITE: "false"
  DB_PORT: "5432"
  MAX_WORKERS: {{ .Values.workerPool.maxWorkers | quote }}
  MAX_QUEUE: {{ .Values.workerPool.maxQueue | quote }}
  {{- if .Values.workerPool.jobs.helmRevisions.enabled -}}
  REVISIONS_COUNT: {{ .Values.workerPool.jobs.helmRevisions.revisionsCount | quote }}
  {{- end -}}
  {{- if .Values.workerPool.jobs.previewTtl.enabled -}}
  PREVIEW_DEPLOYMENTS_TTL: {{ .Values.workerPool.jobs.previewTtl.ttl | quote }}
  {{- end -}}
{{- end -}}
