{{- if .Values.workerPool.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "porter.fullname" . }}-worker-pool-env-secret
  labels:
    {{- include "porter.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.workerPool.jobs.helmRevisions.enabled -}}
  AWS_ACCESS_KEY_ID: {{ .Values.workerPool.jobs.helmRevisions.awsAccessKeyId | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.workerPool.jobs.helmRevisions.awsSecretAccessKey | b64enc | quote }}
  AWS_REGION: {{ .Values.workerPool.jobs.helmRevisions.awsRegion | b64enc | quote }}
  S3_BUCKET_NAME: {{ .Values.workerPool.jobs.helmRevisions.s3BucketName | b64enc | quote }}
  S3_ENCRYPTION_KEY: {{ .Values.workerPool.jobs.helmRevisions.s3EncryptionKey | b64enc | quote }}
  {{- end -}}
{{- end -}}
